Check the page size in PageValidator
Aitia-IIOT/ah5-common-java-spring pull request #10
Opened 2024-10-01 13:30 UTC by Katinka666

2024-10-02 09:05 UTC, rbocsi commented on common-utils/src/main/java/eu/arrowhead/common/service/validation/PageValidator.java
> +
This is good. But you have to modify PageService as well. Whenever we use Integer.MAX_SIZE in the code we should use this maxPageSize instead.

2024-10-02 09:05 UTC, rbocsi requested changes
see inline comments

2024-10-04 11:01 UTC, rbocsi approved these changes

2024-10-04 12:29 UTC, borditamas approved these changes

2024-10-05 15:37 UTC, merged