Rb/small issues
Aitia-IIOT/ah5-common-java-spring pull request #18
Opened 2024-12-02 13:59 UTC by rbocsi

2024-12-02 18:24 UTC, Katinka666 requested changes

2024-12-02 18:24 UTC, Katinka666 commented on common-utils/src/main/java/eu/arrowhead/common/intf/properties/validators/NotEmptyStringSetValidator.java
> +						if (Utilities.isEmpty(str)) {
Why is it better? I think we should check if the trimmed string is empty. Maybe `if (Utilities.isEmpty(str.trim()))` ?

2024-12-02 18:24 UTC, Katinka666 commented on common-utils/src/main/java/eu/arrowhead/common/service/validation/meta/evaluator/InEvaluator.java
> +		if (right instanceof final  List<?> rightList) {
I think there is duplicated space after _final_ 🥲

2025-01-06 09:47 UTC, rbocsi commented on common-utils/src/main/java/eu/arrowhead/common/service/validation/meta/evaluator/InEvaluator.java
> +		if (right instanceof final  List<?> rightList) {
fixed

2025-01-14 08:21 UTC, borditamas approved these changes

2025-01-14 08:45 UTC, merged